# Generated by Django 5.1.7 on 2025-03-12 15:44

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('stats', models.JSONField()),
            ],
        ),
    ]
